#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
npm run format ||
(
    echo 'Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

npm run lint
(
    echo 'Eslint Check Failed. Try running npm run lint, add changes and try commit again.';
    false;
)

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'